from pathlib import Path
from tqdm import tqdm

p = Path('C:/Users/smarotta/Desktop/trasc_ann/test')
files = list(p.glob('**/*.txt'))

ok_segments = [
    "tutta la situazione e tutto questo mi è stato riferito dalla banca",
    "avevo già parlato con il impiegato",
    "stralcio e abbiamo compiuto un accordo",
    "io ho fatto un accordo con Banca proprio sto pagando",
    "ci riaggiorniamo lunedì",
    "proviamo ad aggiornarci poi a metà mese signora",
    "domani chiamo di nuovo",
    "spero di poterla richiamare magari prossima settimana",
    "mi deve arrivare di disponibilità",
    "sto aspettando un bonifico",
    "e il 22 di febbraio non ho preso ancora stipendio",
    "mi deve richiamare più tardi adesso sto lavorando",
    "io posso chiamare domani casomai",
    "va bene allora ci risentiamo fra un po' di un po' di giorni grazie",
    "le posso fare sapere tra qualche giorno",
    "no io non sono la moglie",
    "no in questo momento non è con me",
    "oggi non è in azienda",
    "al momento non c'è",
    "solo che adesso so che a lavoro e non vi risponderà ha cambiato la dovete chiamare dopo le 17 e 30",
    "metto la promessa del giorno 23 attende il pagamento va bene",
    "io metto il primo pagamento per il 10 il secondo pagamento per il 10 di aprile",
    "ci eravamo accordati per pagamenti rateizzati",
    "mi doveva versare il saldo le altre 140 è stato fatto il pagamento",
    "entro venerdì riesce a effettuare questo pagamento",
    "mi raccomando di fare il possibile entro venerdì",
    "io domani mattina vado in banca e mi faccio fare l'estratto di di agosto",
    "avvisato la filiale di competenza",
    "vado dal direttore della filiale di riferimento",
    "io il problema adesso sono fuori vedo se riesco a rintracciare il direttore della banca domani mattina ok parlo con lui",
    "adesso provo a sentire la mia banca perché avevo dato in mano tutto a loro per l'estinzione",
    "lunedì vado vado direttamente in banca",
    "io ho chiuso il conto",
    "io non ho più usato quel conto da tanto tempo",
    "ho fatto un bonifico prima",
    "ho pagato al 31",
    "io sono andato a pagare guardi la mia parte",
    "il pagamento l'ho fatto stamattina",
    "ho versato 700 € e ora ti mando subito trovo subito il mandato subito",
    "abbiamo sempre pagato la rata",
    "mi dica lei entro quando va fatto",
    "senta il pagamento come dovrei farlo",
    "volevo qualche informazione in più per per il pagamento",
    "volevo capire un attimino come procedere",
    "come avviene il rimborso",
    "mi scusi dopodomani giusto quando lo devo fare",
    "voglio sapere come devo fare per pagarle",
    "uno sconfinamento di 200 €",
    "c' era un importo scoperto di 559 €",
    "di un debito di 1.382 €",
    "risulta un insoluto di 200 €",
    "la informo che il suo saldo e la sua scopertura di conto è di 952 €",
    "non ho soldi non lavoro",
    "cassa integrazione",
    "attualmente è disoccupato",
    "so io purtroppo sono stato licenziato",
    "non c'ho soldi",
    "le mando l'IBAN",
    "le mando un messaggino su questo numero di cellulare con tutti gli estremi",
    "quindi le mando gli importi in modo tale che lei ha tutto il riferimento",
    "le mando su questo numero di cellulare,S0: tutte le coordinate sia per eseguire il pagamento",
    "in tabaccheria col codice cliente",
    "le invierò un sms sul cellulare per eseguire il pagamento",
    "mia madre e prende la pensione e mi aiuta",
    "ma papà che saltuariamente qualche lavoro lo faccio ma mi faccio aiutare a pagare il mutuo",
    "perché io adesso sto ancora pagando e mi stava facendo aiutare dai miei genitori a pagare il mutuo",
    "farei prestare dall'amico",
    "ho mandato in questo momento con i documenti che vanno stampati e firmati e poi rimandati",
    "ok io devo dire che la banca le invia la tutta la documentazione e gliela invio sia la proposta del piano di rientro mensile sia il format da compilare",
    "appunto entro il 20 riesce a farmela avere firmato a nome del signor",
    "allegherà la modulistica la carta la copia della carta d'identità,S0: sì corso di validità e la tessera sanitaria",
    "modulistica anche copia fronte retro della carta d'identità",
    "nuovamente in banca verifichi tutto quello che le ho detto",
    "lei comunque comunichi con la banca",
    "dico verifichi tutte queste cose chiami la signora della filiale e poi ci risentiamo",
    "signora non so vuole informarsi lei presso la filiale",
    "si rechi in banca e verifichi quanto le ho detto",
    "faccia una verifica nella sua azienda",
    "magari li contatta lei magari si reca filiale",
    "l' ammontare del totale dovremmo dare quant' è",
    "quale sarebbero la fattura",
    "ho capito ma quant' è questa rata",
    "quando effettuerà questo versamento",
    "quindi effe ha effettuato il bonifico",
    "ha eseguito il pagamento",
    "io devo andare a un legale",
    "c'è uno sbaglio io vi vado a denunciare",
    "sono la dottoressa la chiamo dall'Italia dall'ufficio della per conto della Banca",
    "pronto sì buongiorno la contatta dalla dall'sono l'operatore il signor",
    "mi faccio portavoce io me ne faccio 2 di cause",
    "m' è arrivato un atto giudiziario che devo presentarmi in Tribunale",
    "io adesso l'appuntamento con l'avvocato",
    "vi era stata proposta anche la possibilità di una chiusura transattiva",
    "le posso proporre un rateizzo",
    "possiamo accordarci e pagare un pochino alla volta",
    "possiamo procedere anche facendo una rateizzazione",
    "acconto del 50% di quello che ci è scaduto più possiamo proporre a 4 rate",
    "non riesce a fare nemmeno la rateizzazione 100 € al mese",
    "e se vuole pagare in 2 rate signora se lei proviamo in 2 rate",
    "me possiamo anche accordarci per un pagamento in 2 soluzioni",
    "per questo non deve avere problemi è possibile anche rateizza",
    "le posso dire un pagamento dividere in questo momento se mi danno la possibilità metà lunedì e metà il lunedì successivo ma non possiamo andare oltre",
    "50 € al mese",
    "nemmeno 50 € al mese",
    "autorizzato un piano di rientro",
    "mi può fornire il suo numero di telefono dove le mandi gli estremi per il pagamento",
    "mi dà un numero di telefono per parlare con un",
    "sì mi dia il suo indirizzo mail",
    "va bene allora facciamo stralcio via",
    "invece il conto personale quindi chiedo gentilmente di aspettarmi ancora qualche giorno",
    "volevo chiedere ma voi fate delle dilazioni piano di rientro",
    "la richiesta di sospensione momentanea del mutuo perché non stiamo lavorando",
    "avevo fatto anche una domanda per proseguire con la sospensione",
    "stavo parlando pensando con il mio avvocato di far avere a voi una proposta di saldo stralcio",
    "io avevo chiesto la rateizzazione",
    "attendevo il modulo firmato",
    "lei scrive come intende pagare mi gira questa copia e io la sottopongo ad",
    "invitandomi la ricevuta del del del versamento",
    "mi fa pervenire la copia contabile",
    "per inviare la copia del bonifico effettuato",
    "io non pago niente",
    "non ho proprio possibilità io mi dispiace",
    "non ho pagato e non ti do una lira",
    "le rate che rimangono da pagare non le voglio pagare",
    "non possiamo pagarla adesso",
    "io ho già spiegato perché non li pago",
    "la situazione è che sono in ospedale grazie,S1: 3 mesi e ne ho ancora",
    "stata operata ho avuto dei problemi di salute",
    "ho una una una patologia",
    "possiamo richiedere un'autorizzazione ma per il 5 di maggio che è la scadenza",
    "pagamento deve essere fatto entro lunedì",
    "prima rata scadenza 5 gennaio",
    "venerdì è la mia ultima data dopodiché devo chiudere la pratica",
    "dobbiamo chiudere la pratica entro fine anno",
    "entro praticamente il 4 febbraio",
    "io farò il bonifico",
    "quando arriva in banca dopo vi faccio fare un bonifico",
    "mo' ti posso pagare le 2 rate che non ce l'ho pagata",
    "mattina lo pago",
    "io intendo pagare tutti in tutto in tutto in unica soluzione",
    "c'è modo di fare un pagamento almeno parziale",
    "mi dica un attimo come vuole pagare",
    "io sono qua a capire se lei ha intenzione di pagare o meno",
    "se riuscite a sanare quindi a rientrare dal dallo scoperto",
    "vorremmo capire le sue intenzioni"
]
non_ok_segments = [
    "tipo di accordo avete preso",
    "aveva comunicato che la sua banca procedeva all'estinzione",
    "continuare a pagare la rata che sto facendo",
    "si può fare cioè trasferire questo contratto su un nuovo",
    "adesso le passo la ragazza della dell'agenzia",
    "e io sto pagando quindi pagando",
    "la rata mi ha detto parte poi dal primo di ogni mese dalla pensione questa cosa qua io non c'è chi fa che ho detto noi siamo tranquilli perché fa tirandole giù direttamente dalla pensione questo problema non sussiste tirando una rata",
    "tiamo facendo un piano di rientro",
    "ho visto l'applicazione le una rateizzazione dal 3 sei",
    "mi veniva ritirato il 15",
    "può dare il mio recapito",
    "martedì mattina",
    "attendiamo glielo faccio pervenire otteniamo contatto dal suo legale",
    "a contatto domani allora per avere conferma",
    "va bene o domani mattina eventualmente v",
    "sto arrivando la tensione",
    "non è facile per sbloccare",
    "signora a fine mese",
    "gli mancava soltanto una fattura da approvare proprio che stavo cercando ma non non sollecito lentamente perché sennò",
    "non si poteva attendere entro il giorno uno diversamente gli accordi decadono",
    "va bene sospendiamo aggiornate",
    "non sono in Italia",
    "la contatto poi davanti al direttore",
    "perché ha fatto il vaccino e non so come so domani capito allora fatto infatti non un terzo",
    "non lo so e non non adesso non lo so perché non sto bene",
    "signor mezza 3 e mezzo che ok grazie",
    "ogni settimana sì",
    "sono impegnato",
    "noi no",
    "la signora quando la trovo ",
    "non mi ha risposto",
    "ah il signor non c'",
    "la nipote prego",
    "mia cognata",
    "nel tardo pomeriggio verso",
    "entro il 20 aprile",
    "virgola 86 diviso 2 rate ogni volta è dell'importo di 138,95 €",
    "la chiamavo per per il secondo versamento quello da 67 67",
    "questa richiesta non risulta da nessuna parte",
    "allora quindi 151,29 € e poi l'altra facciamo un piano di rientro con 100 € al mese",
    "Devo andare",
    "sto verificando",
    "per avere prima di tutto il totale e poi soprattutto eh chiude il saldo probabilmente sarà lo farò",
    "allora io adesso la sto chiamando per chiudere questa situazione",
    "va bene allora io dico se c'è stata la ricevuta",
    "la dottoressa m' ha detto che a un certo punto si è arrivato ad lei lo leggerà poi dopo faceva prelevato dal mio conto dal mio conto e 171 € o 172 quelli che sono e poi faceva guardarla poi le mandava i soldi adesso",
    "dico che ci vado domani mattina",
    "lei non deve contattarmi",
    "non posso controllare immediatamente per quello",
    "devo controllare",
    "da 5 anni che vado avanti con loro",
    "quando ho chiamato a febbraio marzo e m' ha detto sì sì scendemmo il contratto le manderemo qualcuno a prendere il modem quindi io mi sono tra virgolette fidati",
    "io non ho ricevuto perché è stato interrotto",
    "già venerdì",
    "gliela invio subito via e-mail",
    "l' ho fatto stamattina",
    "ho già provveduto",
    "sì sì sì grazie signora stamattina",
    "abbiamo già fatto tutto ieri guardi",
    "come data ultima è oggi,S0: per il bonifico altrimenti dovrebbe recarsi in una nostra agenzia dove ci può anche pagare in contanti",
    "lei avrà il bonifico",
    "mi faccio subito il bonifico",
    "per caso tramite bonifico come le viene più comodo,S0: lo facciamo le cose venerdì io posso andare a versare una giornata se riesce a guarda",
    "le faccio il bonifico",
    "adesso per fare il bonifico come",
    "chiedere cosa deve chiedere in dove poi vado alla posta riguardo",
    "va bene farò questo alla posta",
    "esattamente settembre ottobre 2 mila e 21",
    "rata di novembre",
    "non ha nessuna possibilità nemmeno di fare delle piccole rate",
    "non ce la faccio",
    "le mando un sms normale",
    "sì nei messaggi sms ieri sera ha mandato una,S100: non me lo rimanda",
    "ecco se se me lo dà per sicurezza",
    "ce la fa a farmi avere riscontro",
    "le mando tutto allora",
    "gliela invio con un sms o con una mail",
    "on ha nessuno completamente chi la sta assistendo quindi porta da mangiare chi le fa la spesa chi chi l'aiuta",
    "i miei genitori non posso aiutarmi",
    "i miei familiari non lavorano non lavorano stabilmente",
    "nessuno che possa dare una mano",
    "no no bollettino a casa no",
    "gliela rimando subito",
    "insistere oggi pomeriggio lei rientra da e lo faccio subito glielo mando",
    "io gliela invio con una mail tutti gli estremi per effettuare il pagamento dalle una mia mail così poi io la stampa",
    "io gliela rimando di nuovo l'e-mail",
    "va be' io lo mando",
    "devo fare la coda mandargliela",
    "altrimenti il conto continuando a rimanere aperto con maturare ovviamente tutte quelle che sono le spese di tenuta contotesto insufficiente",
    "sistemate queste questi 2 conti signora",
    "veda se è andata a buon fine,S0: se non è rimasto delle sospesi la controllare",
    "brava gli telefonicamente sbagliato e mi avete fatto un bollettino di 75 invece di 78,50 € e 50",
    "va da in banca magari ",
    "le dico se riesce a farsi fare la ricevuta di questo pagamento",
    "deve provvedere a chiuderlo signora se lei lo chiude",
    "verso il 7 l'8 di di di di di di aprile ci deve andare",
    "se lei vede l'ultimo movimento e lei vede che c'è un addebito",
    "la cifra ",
    "le posso dare una",
    "lei mi ha detto il 16 me lo conferma quindi",
    "è entrata ieri 100 € per inciso",
    "non ha provveduto",
    "non avrei disturbata",
    "Sì",
    "sì no no l'ho fatto il bonifico",
    "3 giorni fa",
    "oggi non riesce ad andare",
    "ancora non vediamo la contabilizzazione",
    "No",
    "mio marito è stato anche lui a casa lui ha avuto anche la febbre per fortuna guardia va fatto tampone non siamo così",
    "un totale di 9.450",
    "devo fare",
    "no glielo mando nel pomeriggio",
    "fa sacrifici per pagarsi gli interessi che maturano su questo importo",
    "la signora dall'Italia",
    "da per conto di",
    "e per la cessione del quinto",
    "dall' Italia per",
    "una denuncia di furto",
    "quanto meno cerchiamo di essere costante nei pagamenti anche 100 € al mese però cerchiamo di farli",
    "no è questo le stavo dicendo quello non non ha chiesto di poter sospendere",
    "più che altro per capire se vuole risolvere se risparmia",
    "e stavo facendo il conteggio per capire quanto riusciamo a fare il più possibile visto pure questa situazione",
    "la necessità di fare un rientro più rapido della posizione",
    "ilazionare adesso un po' questi 900 €",
    "k riesce a trovare un accordo",
    "sentiamoci noi la prossima settimana con calma",
    "è possibile un rateizza",
    "le la cifra minima come rata è di 70 €",
    "l' unica cosa io posso fare ed è l'ultima possibilità che probabilmente mi daranno è lunedì e lunedì più di questo non posso fare",
    "50,60 € 58 58 € la rata va bene",
    "l' unica cosa che possiamo fare è cercare di rientrare o ancor meglio se lei può pagare l'intero importo",
    "il numero di cellulare",
    "eh sì sì me la dia signora",
    "va bene signora d'accordo allora lavoro subito la pratica gli mando la mail",
    "sì mi faccia la cortesia così evito di disturbarla oltremodo signora mi dica",
    "un indirizzo di posta elettronica",
    "la banca di solito deve arrivare al 65% però vediamo quello di quello dobbiamo valutare senza che dobbiamo un attimo capire",
    "indirizzo di fare un bollettino in invece se lo posso fare",
    "non so se era possibile effettuare magari una un veicolo per volta",
    "eventualmente se ci concedete di fare un piano di guastatori cominciamo a fare una situazione perché noi ora momentaneamente 500 € non li possiamo uscire",
    "esatto una proposta per 700 €",
    "ne dobbiamo incanalare alla fine del finanziamento",
    "e quant' è 3,S0: allora no no no no no no lei paga 2 solamente,S12: visto che stiamo investendo accusando 2 come sono 2,S0: percento signor o non,S12: lo sa non 75",
    "avevamo fatto un'offerta di 500 € a fare tutto",
    "buttare la perdita l'80%",
    "signora facciamo 3 rate così si chiude",
    "la possibilità di fare una proposta",
    "io entro il 10 maggio voglio ritirare questi soldi,S0: per io il 10 fare diversamente qualche pagarla regolarmente lasciata mi dà la possibilità entro questo periodo",
    "per capire se ci fosse o meno interessato a risolvere bonariamente prima del passaggio alla fase legale",
    "non si può non c'è neanche la possibilità di poter trovare un accordo",
    "mi ha detto di fare una proposta noi di quello che possiamo offrire tutti i mesi",
    "potremmo farne sei da 400 eventualmente",
    "essendo stata accettata da questo mese",
    "rispedire al mio indirizzo che adesso le mando sempre via e-mail",
    "entro venerdì dovremmo averlo va bene signor attendiamo",
    "non è avvenuto il pagamento",
    "ancora non è arrivato",
    "se era stato effettuato l'altro versamento perché ancora non risulta",
    "io non non sono in condizioni di di veramente di di adempiere a niente",
    "quando tempo vado",
    "per il momento no",
    "io non devo assolutamente che paga",
    "ho capito devo pertanto ritenere che lei rifiuta il pagamento la relazione in questo modo",
    "non lo faccio",
    "succede l'incidente loro non mi hanno dato niente",
    "io sto a posto",
    "ok allora devo aspettare i tempi tecnici",
    "attualmente no",
    "non gliela do",
    "televisione come le ho preso l'ho buttata",
    "io non ce l'ho i soldi mi dispiace",
    "non le ho detto sono adesso sono a casa e non posso neanche uscire,S25: un casino che adesso devo fare quarantina",
    "mi è mancato il mio papà",
    "siamo un attimo ridotti qua in ufficio per colpa dei contatti",
    "ma ripeto ci siamo trovati un po' tutti in una situazione un po' difficile e quindi",
    "Domani",
    "la posizione poi non riesce più a contabilizzarla",
    "perché io il 28 di gennaio",
    "quando ha intenzione di effettuare questo versamento",
    "domani restituiamo tutto",
    "perché la posizione non riusciamo a trattenerlo a fine",
    "può pagare capitale è oneri ma mi domani",
    "a partire da maggio",
    "domani il bonifico mi sa che non lo possiamo interessare,S0: perché e perché la contabilità viene chiusa oggi",
    "ha detto quando posso",
    "verrà fatto l'ho fatto a fine mese",
    "ora lo faccio",
    "quando arriva la pensione ",
    "il mese prossimo si dovrebbe riprendiamo le mando qualcosa di più di un mese",
    "nel momento in cui verrà formulata la successione è chiaro che poi dovrete andare in filiale per risolvere ",
    "vado a fare il versamento",
    "ho messo in vendita",
    "riesce a farlo possiamo aiutarla in qualche modo",
    "le do tempo magari una settimana",
    "ok però dico tanto le nuvole onorare il debito con la banca e così per restituire i soldi",
    "io le sto dicendo di trovare un accordo"
]

for segment in non_ok_segments:
    for f in tqdm(files):
        name = f.name
        with open(f, "r", encoding="UTF8") as file:
            content = file.read()
            if segment in content:
                print(f"{name}\t{segment}")
                # print(content)
